
[general]
app_name = "V V V V"
debug = true

[api_url]

# Docker need to load dynamic server url. No need to hardcode here.
#api_base_url = "http://127.0.0.1:8000/"

auth_login = "admin/auth/login"
is_logged_in = "admin/auth/is_logged_in"

agent_login = "agent/login"
agent_is_logged_in = "agent/is_logged_in"

auth_signup = "admin/auth/signup"
agent_signup = "agent/signup"

auth_changepassword = "admin/auth/changepassword"
agent_changepassword = "agent/change_password"

auth_logout = "admin/auth/logout"
agent_logout = "agent/logout"

list_states = "admin/states"
add_state = "admin/add_state"
update_state = "admin/update_state"
delete_state = "admin/delete_state"

list_districts = "admin/districts_list"
add_district = "admin/add_district"
update_district = "admin/update_district"
delete_district = "admin/delete_district"

list_constituencies = "admin/assemblyconstituency"
add_constituency = "admin/add_constituency"
update_constituency = "admin/update_constituency"
delete_constituency = "admin/delete_constituency"


list_parties = "/admin/politicalparties_list"
add_party = "/admin/add_politicalparty"
delete_party = "/admin/delete_politicalparty"

upload_polling_booths = "admin/upload_pollingstations"
list_polling_booths = "admin/list_pollingstations"
download_polling_booths = "admin/download_pollingstations"

upload_voters = "admin/upload_voters"
list_voters = "admin/list_voters"
download_voters = "admin/download_voters"


[theme]
primaryColor="#1b4332"
backgroundColor="#fff"
secondaryBackgroundColor="#e9ecef"
textColor="#000"
font="sans serif"


[client]

# Whether to enable st.cache.
# Default: true
caching = false


[logger]

toolbarMode = "developer"